# -*- coding: utf-8 -*-
"""
admin_ai.registry — loads admin_ai\\capabilities.json (curated, hand-
written) and validates every entry against admin_ai\\capability_index.json
(generated by index_builder.py from the CURRENT panel_bot.py/main.py).
Invalid entries are disabled individually with a recorded reason; only
entries that survive validation are ever selectable by the model (their
ids are what schema.build_response_schema() turns into the enum).

Structural safety invariant enforced here (not just documented): a
capability with risk="confirm_gated" (destructive/spend) can NEVER be
kind="command" — it may only be kind="menu"/"wizard", i.e. it can only
route the admin to an EXISTING preview/confirmation screen, never trigger
a controller command directly.

Pure stdlib (json/re/dataclasses). No panel_bot/main/telethon imports.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

ALLOWED_KINDS = frozenset({"menu", "command", "wizard"})
ALLOWED_RISKS = frozenset({"read", "action", "confirm_gated"})
DEFAULT_INVALID_RATIO_FAIL_CLOSED = 0.30

_PLACEHOLDER_RE = re.compile(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}")


@dataclass
class Capability:
    id: str
    title: str
    synonyms: List[str]
    kind: str
    target: Dict[str, Any]
    risk: str
    entity_slots: List[str]
    menu_path: List[str]
    llm_description: str
    command_template: Optional[str] = None
    enabled: bool = True
    disabled_reason: Optional[str] = None


@dataclass
class RegistryLoadResult:
    capabilities: List[Capability] = field(default_factory=list)
    status: str = "ready"  # "ready" | "degraded" | "fail_closed"
    total_count: int = 0
    enabled_count: int = 0
    disabled_count: int = 0
    disabled: List[Dict[str, str]] = field(default_factory=list)  # [{"id": ..., "reason": ...}]
    index_semantic_hash: Optional[str] = None

    def enabled_ids(self) -> List[str]:
        return [c.id for c in self.capabilities if c.enabled]

    def get(self, capability_id: str) -> Optional[Capability]:
        for c in self.capabilities:
            if c.id == capability_id and c.enabled:
                return c
        return None


def load_capabilities_file(path: Union[str, Path]) -> List[Dict[str, Any]]:
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    return list(data.get("capabilities", []))


def load_index_file(path: Union[str, Path]) -> Dict[str, Any]:
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def _command_word(template: str) -> str:
    return str(template or "").strip().split(" ", 1)[0]


def _template_placeholders(template: str) -> List[str]:
    return _PLACEHOLDER_RE.findall(template or "")


def validate_entry(entry: Dict[str, Any], index: Dict[str, Any]) -> Optional[str]:
    """Return an error-reason string if `entry` is invalid against `index`,
    else None. Pure function — no side effects, safe to unit-test directly.
    """
    cid = entry.get("id")
    if not cid or not isinstance(cid, str):
        return "missing/invalid id"

    kind = entry.get("kind")
    if kind not in ALLOWED_KINDS:
        return f"invalid kind: {kind!r}"

    risk = entry.get("risk")
    if risk not in ALLOWED_RISKS:
        return f"invalid risk: {risk!r}"

    entity_slots = entry.get("entity_slots")
    if entity_slots is None:
        entity_slots = []
    if not isinstance(entity_slots, list):
        return "entity_slots must be a list"

    # Hard structural invariant (see module docstring).
    if risk == "confirm_gated" and kind == "command":
        return "confirm_gated capability must not be kind=command (destructive/spend must route to an existing preview/confirm screen, never a direct command)"

    target = entry.get("target") or {}
    if not isinstance(target, dict):
        return "target must be an object"

    menu_keys = index.get("menu_keys", {}) or {}

    if kind == "menu":
        if "menu" in target:
            if target["menu"] not in set(menu_keys.get("exact", [])):
                return f"target.menu {target['menu']!r} not found in capability_index.menu_keys.exact"
        elif "menu_prefix" in target:
            if target["menu_prefix"] not in set(menu_keys.get("prefix", [])):
                return f"target.menu_prefix {target['menu_prefix']!r} not found in capability_index.menu_keys.prefix"
            slot = target.get("entity_slot")
            if not slot or slot not in entity_slots:
                return "menu_prefix target requires target.entity_slot to also be listed in entity_slots"
        else:
            return "kind=menu requires target.menu or target.menu_prefix"

    elif kind == "command":
        template = entry.get("command_template")
        if not template or not isinstance(template, str):
            return "kind=command requires a non-empty command_template"
        word = _command_word(template)
        commands = index.get("commands", {}) or {}
        if word not in set(commands.get("exact", [])):
            return f"command_template word {word!r} not found in capability_index.commands.exact"
        for placeholder in _template_placeholders(template):
            if placeholder not in entity_slots:
                return f"command_template placeholder {{{placeholder}}} is not declared in entity_slots"

    elif kind == "wizard":
        if "wizard" not in target:
            return "kind=wizard requires target.wizard"
        # Wizard names are not AST-extracted into capability_index.json in
        # the P0 scope (menu keys / callback data / commands only), so
        # structural presence is all that's checked here. A future index
        # milestone may add wizard-name extraction for stronger validation.

    return None


def load_registry(
    capabilities_path: Union[str, Path],
    index_path: Union[str, Path],
    *,
    invalid_ratio_fail_closed: float = DEFAULT_INVALID_RATIO_FAIL_CLOSED,
) -> RegistryLoadResult:
    entries = load_capabilities_file(capabilities_path)
    index = load_index_file(index_path)

    caps: List[Capability] = []
    disabled: List[Dict[str, str]] = []
    seen_ids: set = set()

    for entry in entries:
        raw_id = entry.get("id")
        cid = raw_id if isinstance(raw_id, str) and raw_id else f"<unnamed:{len(caps)}>"

        reason = validate_entry(entry, index)
        if reason is None and cid in seen_ids:
            reason = "duplicate capability id"
        seen_ids.add(cid)

        cap = Capability(
            id=cid,
            title=str(entry.get("title", cid)),
            synonyms=list(entry.get("synonyms") or []),
            kind=str(entry.get("kind", "")),
            target=dict(entry.get("target") or {}),
            risk=str(entry.get("risk", "")),
            entity_slots=list(entry.get("entity_slots") or []),
            menu_path=list(entry.get("menu_path") or []),
            llm_description=str(entry.get("llm_description", "")),
            command_template=entry.get("command_template"),
            enabled=reason is None,
            disabled_reason=reason,
        )
        caps.append(cap)
        if reason is not None:
            disabled.append({"id": cid, "reason": reason})

    total = len(caps)
    disabled_count = len(disabled)
    invalid_ratio = (disabled_count / total) if total else 1.0

    if total == 0:
        status = "fail_closed"
    elif invalid_ratio > invalid_ratio_fail_closed:
        # Fail CLOSED: too much of the curated file has drifted from the
        # current codebase to trust ANY of it -- disable every entry
        # (including ones that individually validated fine) rather than
        # serve a mostly-broken registry.
        status = "fail_closed"
        for c in caps:
            if c.enabled:
                c.enabled = False
                c.disabled_reason = (
                    f"registry fail-closed: invalid ratio {invalid_ratio:.0%} "
                    f"exceeds threshold {invalid_ratio_fail_closed:.0%}"
                )
                disabled.append({"id": c.id, "reason": c.disabled_reason})
        disabled_count = total
    elif disabled_count:
        status = "degraded"
    else:
        status = "ready"

    enabled_count = total - disabled_count

    return RegistryLoadResult(
        capabilities=caps,
        status=status,
        total_count=total,
        enabled_count=enabled_count,
        disabled_count=disabled_count,
        disabled=disabled,
        index_semantic_hash=index.get("semantic_hash"),
    )
