# -*- coding: utf-8 -*-
from __future__ import annotations

"""Human-facing texts for the lead-tracker version of ALM_TPilot / TPilot."""

TWINE_MISMATCH_TEXT = ""  # compatibility export; Twine is not used in this version.


PROFILE_QUESTION_TEXT = 'Здравствуйте! Подскажите, пожалуйста, из какого вы города и ваш возраст. Эта информация нужна для работы.'
OFFLINE_NOTICE_TEXT = 'Здравствуйте, сейчас нерабочее время, с радостью ответим вам на все вопросы в рабочее время!'
PROFILE_SAMPLE_HINT_TEXT = 'Можете просто одним сообщением, например Москва 24.'
UA_REDIRECT_TEXT = 'У нас є для вас чудова робота, яка кожному подобається за змістом і по грошах, які наші люди заробляють перебуваючи вдома. Цим займається фахівець Едуард, напишіть йому в Telegram https://t.me/ALM_Charter'
PROFILE_SUCCESS_TEXT = 'Спасибо за ответ!\nМожете чуть подробнее рассказать о вашем опыте? Например, где работали, какие задачи выполняли.\nТак я смогу предложить вам наиболее подходящий вариант.'
PROFILE_NON_RU_FINAL_TEXT = 'Спасибо за ответ!\nМожете чуть подробнее рассказать о вашем опыте? Например, где работали, какие задачи выполняли. И как вы относитесь к командировке в РФ, если зарплата будет от 5000$?\nТак я смогу предложить вам наиболее подходящий вариант.'
PROFILE_UNKNOWN_TEXT = 'Супер, есть ещё один вопрос, сейчас напишу.'
PROFILE_NONLIQUID_COUNTRY_TEXT_TEMPLATE = 'Ага, понятно, вы указали страну {country}.'
CLARIFY_AGE_TEXT = 'Подскажите, пожалуйста, ваш возраст.'
CLARIFY_GEO_TEXT = 'Подскажите, пожалуйста, из какого вы города.'
CLARIFY_BOTH_TEXT = 'Подскажите, пожалуйста, из какого вы города и ваш возраст.'


def build_manager_help_text() -> str:
    lines = [
        "📌 TPilot Lead Tracker",
        "",
        "Рабочая группа статистики: AI_STAT.",
        "Отдельная группа статусов: WORK_STATUS, если задан WORK_STATUS_CHAT_ID.",
        "",
        "📊 Статистика",
        "/stat all - статистика за сегодня по всем менеджерам",
        "/stat <manager_key> - статистика за сегодня по одному менеджеру",
        "/stat det - детальная статистика за окно 08:00-17:00 по всем менеджерам",
        "/stat det all - детальная статистика за окно 08:00-17:00 по всем менеджерам",
        "/stat det <manager_key> - детальная статистика за окно 08:00-17:00 по одному менеджеру",
        "/flight all - долёты за окно 17:00-08:00 по всем менеджерам",
        "/flight <manager_key> - долёты за окно 17:00-08:00 по одному менеджеру",
        "/stat range all 01.05.26 06.05.26 - статистика за период",
        "/stat range te 01.05.26 06.05.26 - статистика менеджера за период",
        "",
        "🔔 Неотвеченные",
        "/unanswered all - показать клиентов, которым менеджеры не ответили",
        "/unanswered <manager_key> - неотвеченные по менеджеру",
        "/unanswered_notify status - статус автоуведомлений по неотвеченным в PanelBot",
        "/unanswered_notify on - включить автоуведомления по неотвеченным в PanelBot",
        "/unanswered_notify off - выключить автоуведомления по неотвеченным в PanelBot",
        "",
        "🧪 Тесты и база",
        "/testlead reset <chat_id> - очистить тестового лида, чтобы он снова считался новым",
        "/testlead status <chat_id> - проверить следы лида в базах менеджеров",
        "/baseline create <manager_key|all> - пометить текущие личные чаты как старые",
        "/baseline status <manager_key|all> - показать список старых чатов",
        "/baseline clear <manager_key|all> confirm - очистить список старых чатов",
        "",
        "💬 Автоответы клиентам",
        "/autoreply status all - статус автоответов по всем менеджерам",
        "/autoreply auto <manager_key|all> - авто по графику",
        "/autoreply silent <manager_key|all> - не писать клиентам",
        "/autoreply now <manager_key|all> - анкета сейчас, даже вне графика",
        "/silent manager on|off <manager_key|all> - включить или выключить полный тихий режим менеджера",
        "/silent source on|off <source_key> - включить или выключить полный тихий режим источника",
        "/silent group on|off <group_key> - включить или выключить полный тихий режим группы",
        "",
        "📦 Экспорт",
        "/export all - Excel за сегодня по всем менеджерам",
        "/export all 7d - Excel за неделю по всем менеджерам",
        "/export all 31d - Excel за месяц по всем менеджерам",
        "/export <manager_key> - Excel за сегодня по одному менеджеру",
        "/export range all 01.05.26 06.05.26 - Excel за период",
        "/export range te 01.05.26 06.05.26 - Excel менеджера за период",
        "",
        "🟢 Статус работы менеджера, в WORK_STATUS",
        "/online - техническая команда, в панели используется 🤖 Авто по графику",
        "/offline - техническая команда ночного сообщения",
        "/dayoff - техническая команда ночного сообщения",
        "/worknow - техническая команда для ⚡ Анкета сейчас",
        "/status - показать свой статус",
        "",
        "",
        "🤝 Partner Stat Bot для байеров",
        "/partner requests - заявки на доступ от байеров",
        "/partner list - список байеров",
        "/partner approve <user_id> <source_key> - выдать доступ к одному источнику",
        "/partner source <user_id> <source_key> - сменить источник байера",
        "/partner live on|off <user_id> - включить или выключить уведомления о новых лидах",
        "/partner contacts on|off <user_id> - показывать или скрывать chat_id, username, имя и телефон лида",
        "/partner excel on|off <user_id> - разрешить или запретить Excel",
        "/partner format light|pro|both <user_id> - выбрать формат статистики",
        "/partner enable|disable <user_id> - включить или выключить доступ",
        "🧯 Сервис",
        "/help - справка",
        "/instructions - инструкция",
    ]
    return "\n".join(lines).rstrip()


def build_admin_help_text(*, work_start_hour: int = 0, work_end_hour: int = 0, night_mode_enabled: bool = False) -> str:
    _ = (work_start_hour, work_end_hour, night_mode_enabled)
    lines = [
        "📌 Команды TPilot Lead Tracker",
        "",
        "Рабочая логика статистики в AI_STAT_CHAT_ID.",
        "Статусы online/worknow/offline/dayoff работают в WORK_STATUS_CHAT_ID.",
        "TPilot фиксирует каждого входящего лида сразу после первого сообщения менеджеру.",
        "Дополнительно определяет возраст, город, регион, страну, ликвид/неликвид и причины неликвида.",
        "Twine, followups и старая сценарная анкета в этой версии не используются.",
        "____",
        "",
        "📊 Статистика",
        "/stat all - статистика за сегодня по всем аккаунтам",
        "/stat <manager_key> - статистика за сегодня по конкретному аккаунту",
        "/stat det - детальная статистика за 08:00-17:00 по всем аккаунтам",
        "/stat det all - детальная статистика за 08:00-17:00 по всем аккаунтам",
        "/stat det <manager_key> - детальная статистика за 08:00-17:00 по конкретному аккаунту",
        "/flight all - долёты за 17:00-08:00 по всем аккаунтам",
        "/flight <manager_key> - долёты за 17:00-08:00 по конкретному аккаунту",
        "",
        "Статистика показывает:",
        "Всего написавших, новые, дубликаты, ответили возраст/гео, ликвид, неликвид, не определено, причины неликвида.",
        "",
        "🧪 Тесты и база",
        "/testlead reset <chat_id> - очистить тестового лида во всех manager DB, чтобы он снова прошёл как новый",
        "/testlead status <chat_id> - показать, где этот лид ещё есть в базах",
        "/baseline create <manager_key|all> - пометить текущие личные чаты менеджера как старые",
        "/baseline status <manager_key|all> - показать список старых чатов",
        "/baseline clear <manager_key|all> confirm - очистить список старых чатов",
        "",
        "📦 Экспорт",
        "/export all - Excel за сегодня по всем аккаунтам",
        "/export all 7d - Excel за неделю по всем аккаунтам",
        "/export all 31d - Excel за месяц по всем аккаунтам",
        "/export <manager_key> - Excel за сегодня по конкретному аккаунту",
        "",
        "Excel содержит базовые данные лида, возраст, город, регион, страну, статус, причину неликвида, источник гео, режим менеджера, отправку вопроса, offline-сообщение, UA-текст и факт ручного ответа менеджера.",
        "",
        "🟢 WORK_STATUS команды",
        "Менеджер сам:",
        "/online - статус online для своего аккаунта",
        "/offline - статус offline для своего аккаунта",
        "/dayoff - режим выходного для своего аккаунта",
        "/worknow - техническая команда для ⚡ Анкета сейчас",
        "/status - проверить свой статус",
        "",
        "Админ/ответственный:",
        "/online <manager_key> - поставить менеджера online",
        "/offline <manager_key> - поставить менеджера offline",
        "/dayoff <manager_key> - поставить менеджеру выходной",
        "/worknow <manager_key> - включить дневное приветствие и анкету прямо сейчас, даже ночью",
        "/workday <manager_key> - вернуть менеджера в рабочий режим",
        "/status <manager_key> - статус менеджера",
        "/status all - статусы всех менеджеров",
        "",
        "Поведение:",
        "Авто по графику - клиенту отправляется вопрос про город и возраст в рабочее окно 08:00-17:00, если данных ещё нет.",
        "Анкета сейчас - принудительный режим, дневное приветствие и анкета работают прямо сейчас, даже ночью.",
        "Ночное сообщение - клиенту один раз за период отправляется сообщение нерабочего времени, вопрос про город/возраст не отправляется.",
        "Если менеджер вручную ответил любому клиенту, весь аккаунт считается рабочим до 1,5 часа без ручных исходящих сообщений.",
        "Если менеджер вручную ответил конкретному клиенту, программа больше ничего не пишет этому клиенту на любом этапе.",
        "",
        "🇺🇦 Украина",
        "Украина всегда считается неликвидом. При рабочем дневном режиме и определении Украины отправляется отдельный UA-текст с переводом на Эдуарда.",
        "",
        "🕛 Автоотчёты",
        "В 08:00 TPilot отправляет долёты за окно 17:00-08:00.",
        "В 17:00 TPilot отправляет финальную дневную статистику за окно 08:00-17:00.",
        "Старый автоотчёт 23:59 с Excel в этой версии не используется.",
        "",
        "📦 Источники трафика",
        "/source add seo SEO - создать источник",
        "/source link seo te - закрепить менеджера за источником",
        "/source stats all - статистика по источникам",
        "/silent source on seo - тихий режим для всего источника seo",
        "/silent source off seo - снова разрешить автоответы источнику seo",
        "",
        "👥 Группы менеджеров",
        "/mgroup add group1 Группа 1 - создать группу",
        "/mgroup add_manager group1 te - добавить менеджера в группу",
        "/mgroup stats all - статистика по группам",
        "/silent group on group1 - тихий режим для всей группы group1",
        "/silent group off group1 - снова разрешить автоответы группе group1",
        "",
        "📈 Качество и дисциплина",
        "/quality all - общий отчёт качества за сегодня",
        "/quality response - время ответа менеджеров",
        "/quality sla - просроченные SLA 15+",
        "/quality ranking - рейтинг менеджеров",
        "/quality losses - потери лидов",
        "",
        "📊 Воронка и качество источников",
        "/funnel sources - качество источников",
        "/funnel groups - качество групп",
        "/funnel links - связки источник + менеджер",
        "/funnel losses - где теряем лидов",
        "/funnel best - лучшие источники",
        "",
        "👥 Manager registry - только в ЛС TPilot",
        "MANAGER AUTH <пароль> - открыть доступ на 10 минут",
        "MANAGER ADD <key> - создать менеджера",
        "PHONE +79991234567 - отправить код Telegram",
        "CODE 12345 - войти по коду",
        "PASS <пароль_2FA> - пройти 2FA, если требуется",
        "MANAGER LIST - список менеджеров",
        "MANAGER INFO <key> - карточка менеджера",
        "MANAGER PENDING - onboarding в ожидании",
        "MANAGER START <key> - запустить менеджера",
        "MANAGER STOP <key> - остановить менеджера",
        "MANAGER ENABLE <key> - включить менеджера",
        "MANAGER DISABLE <key> - выключить менеджера",
        "MANAGER RESET <key> - сбросить менеджера и начать подключение заново",
        "MANAGER REMOVE <key> - мягко архивировать менеджера",
        "MANAGER RENAME <key> <display_name> - изменить имя в списках",
        "",
        "🛠 PanelBot управление менеджерами",
        "/manager_list - список менеджеров",
        "/manager_info <key> - карточка менеджера",
        "/manager_start <key> - запустить менеджера",
        "/manager_stop <key> - остановить менеджера",
        "/manager_enable <key> - включить менеджера",
        "/manager_disable <key> - приостановить менеджера",
        "/manager_rename <key> <name> - изменить красивое имя",
        "/manager_reset <key> - сбросить авторизацию и заново запросить PHONE/CODE/PASS",
        "/manager_remove <key> - мягко архивировать",
        "/manager_delete_full <key> confirm - удалить из программы с переносом файлов в backup",
        "",
        "🌐 Proxy менеджера",
        "MANAGER PROXY <key> SOCKS5 <host> <port> [login] [password] - сохранить или заменить SOCKS5 proxy и включить его",
        "MANAGER PROXY INFO <key> - показать proxy без пароля",
        "MANAGER PROXY OFF <key> - выключить proxy",
        "MANAGER PROXY ON <key> - включить ранее сохранённый proxy",
        "После изменения proxy перезапустите менеджера через MANAGER STOP <key> и MANAGER START <key>.",
        "В PanelBot в разделе 👥 Менеджеры видно, у кого proxy включён, выключен или не задан.",
        "Через PanelBot можно добавить менеджера пошагово без PHONE/CODE/PASS и настроить proxy по подсказкам.",
        "",
        "🧯 Сервис",
        "/help - справка",
        "/help_ADM - справка",
        "/instructions - инструкция",
    ]
    return "\n".join(lines).rstrip()


def build_instructions_text() -> str:
    lines = [
        "📘 Инструкция ALM_TPilot / TPilot Lead Tracker",
        "",
        "1) Главная логика",
        "Человек написал менеджеру -> лид сразу фиксируется -> событие уходит в STATISTICS -> лид попадает в /stat и /export.",
        "",
        "2) Возраст и гео",
        "Если менеджер online, программа задаёт вопрос:",
        PROFILE_QUESTION_TEXT,
        PROFILE_SAMPLE_HINT_TEXT,
        "",
        "После ответа программа определяет возраст, текущий город, регион, страну, статус и причину неликвида.",
        "Если что-то не определилось, в статистике и Excel будет показано: не определено.",
        "Россия + 18 лет и старше = ликвид. Если страна Россия определена точно, но город не определился, лид считается ликвидом при 18+, город уточняется максимум 2 раза и затем отмечается как не определено.",
        "Не РФ = неликвид с причиной страны. Украина = неликвид и отдельный UA-текст.",
        "",
        "3) Online/offline",
        "Создайте отдельную группу WORK_STATUS и добавьте её ID в .env.TPilot как WORK_STATUS_CHAT_ID.",
        "В панели используются понятные режимы: авто по графику, анкета сейчас, не писать клиентам.",
        "Админ может использовать панель или команды /autoreply auto nik, /autoreply now nik, /autoreply silent nik, /autoreply status nik.",
        "",
        "4) Offline-режим",
        "Если менеджер offline, dayoff, no_show или auto_offline, клиенту один раз за период отправляется:",
        OFFLINE_NOTICE_TEXT,
        "Вопрос про город/возраст в нерабочем режиме не отправляется.",
        "Если менеджер начал отвечать клиентам вручную, аккаунт автоматически возвращается в рабочий режим. Если 1,5 часа нет ручных исходящих ответов в рабочее окно, аккаунт снова переходит в нерабочий режим.",
        "",
        "5) Ручной ответ менеджера",
        "Если менеджер отправил клиенту любое сообщение вручную, программа больше ничего не пишет этому клиенту на любом этапе.",
        "Это блокирует приветствие, вопрос про город/возраст, UA-текст, offline-сообщение и будущие автоответы.",
        "",
        "6) Команды статистики в STATISTICS",
        "/stat all",
        "/stat <manager_key>",
        "/export all",
        "/export <manager_key>",
        "/stat det",
        "/stat det all",
        "/stat det <manager_key>",
        "/flight all",
        "/flight <manager_key>",
        "",
        "7) Файлы-справочники",
        "Для точного определения гео рядом с main.py должны лежать:",
        "router.py",
        "liquid_ru_locations.py - полный файл RU_LOCATIONS",
        "non_liquid_locations.py",
        "ua_locations.py",
        "",
        "8) Manager registry",
        "Новые менеджеры подключаются через ЛС TPilot командами MANAGER AUTH, MANAGER ADD, PHONE, CODE, PASS.",
        "",
        "9) SOCKS5 proxy для менеджеров",
        "Каждому менеджеру можно задать отдельный SOCKS5 proxy через MANAGER PROXY <key> SOCKS5 <host> <port> [login] [password].",
        "Пароль в INFO не показывается. Чтобы заменить proxy, отправьте MANAGER PROXY <key> SOCKS5 ... с новыми данными.",
        "Proxy применяется после перезапуска manager-процесса.",
        "MANAGER PROXY CHECK <key> - проверить SOCKS5 перед PHONE/CODE/PASS.",
        "MANAGER PROXY BYPASS <key> <пароль> - разрешить подключение без proxy через MANAGER_ADMIN_PASSWORD.",
    ]
    return "\n".join(lines).rstrip()


__all__ = [
    "TWINE_MISMATCH_TEXT",
    "PROFILE_QUESTION_TEXT",
    "OFFLINE_NOTICE_TEXT",
    "PROFILE_SAMPLE_HINT_TEXT",
    "UA_REDIRECT_TEXT",
    "PROFILE_SUCCESS_TEXT",
    "PROFILE_NON_RU_FINAL_TEXT",
    "PROFILE_UNKNOWN_TEXT",
    "PROFILE_NONLIQUID_COUNTRY_TEXT_TEMPLATE",
    "CLARIFY_AGE_TEXT",
    "CLARIFY_GEO_TEXT",
    "CLARIFY_BOTH_TEXT",
    "build_manager_help_text",
    "build_admin_help_text",
    "build_instructions_text",
]
