# -*- coding: utf-8 -*-


UA_LOCATIONS = {
    # country tokens
    "украина", "україна", "ukraine", "ua",
    # common cities / translit
    "киев", "київ", "kyiv", "kiev",
    "львов", "львів", "lviv",
    "одесса", "одеса", "odesa", "odessa",
    "харьков", "харьков", "харків", "kharkiv", "kharkov",
    "днепр", "дніпро", "dnipro", "dnepr",
    "запорожье", "запоріжжя", "zaporizhzhia", "zaporozhye",
    "николаев", "миколаїв", "mykolaiv", "nikolaev",
    "херсон", "kherson",
    "чернигов", "чернігів", "chernihiv", "chernigov",
    "сумы", "суми", "sumy",
    "полтава", "poltava",
    "черкассы", "черкаси", "cherkasy",
    "житомир", "zhytomyr",
    "винница", "вінниця", "vinnytsia", "vinnitsa",
    "ровно", "рівне", "rivne", "rovno",
    "луцк", "луцьк", "lutsk",
    "тернополь", "тернопіль", "ternopil",
    "ивано-франковск", "івано-франківськ", "ivano-frankivsk",
    "ужгород", "uzhhorod", "uzhgorod",
    "мукачево", "mukachevo",
    "черновцы", "чернівці", "chernivtsi", "chernovtsy",
    "кропивницкий", "кропивницький", "kropyvnytskyi", "kirovograd",
    "кривой рог", "кривий ріг", "kryvyi rih", "krivoy rog",
    "мариуполь", "mariupol",
    "мелитополь", "melitopol",
    "белая церковь", "біла церква", "bila tserkva", "belaya tserkov",
    # regions / oblasts
    "киевская область", "київська область", "kyivska oblast", "kyiv region",
    "львовская область", "львівська область", "lviv oblast",
    "одесская область", "одеська область", "odesa oblast",
    "харьковская область", "харківська область", "kharkiv oblast",
    "днепропетровская область", "дніпропетровська область", "dnipropetrovsk oblast",
    "запорожская область", "запорізька область", "zaporizhzhia oblast",
    "николаевская область", "миколаївська область", "mykolaiv oblast",
    "херсонская область", "херсонська область", "kherson oblast",
    "сумская область", "сумська область", "sumy oblast",
    "полтавская область", "полтавська область", "poltava oblast",
    "черниговская область", "чернігівська область", "chernihiv oblast",
    "черкасская область", "черкаська область", "cherkasy oblast",
    "житомирская область", "житомирська область", "zhytomyr oblast",
    "винницкая область", "вінницька область", "vinnytsia oblast",
    "ровенская область", "рівненська область", "rivne oblast",
    "волынская область", "волинська область", "volyn oblast",
    "тернопольская область", "тернопільська область", "ternopil oblast",
    "ивано-франковская область", "івано-франківська область", "ivano-frankivsk oblast",
    "закарпатская область", "закарпатська область", "zakarpattia oblast",
    "черновицкая область", "чернівецька область", "chernivtsi oblast",
    "кировоградская область", "кіровоградська область", "kirovohrad oblast",
    "донецкая область", "донецька область", "donetsk oblast",
    "луганская область", "луганська область", "luhansk oblast",
    "хмельницкая область", "хмельницька область", "khmelnytskyi oblast",
}
